### PR TITLE
Add known issue of leading zeroes and corresponding remedies

### LINKED ISSUE #128: [PE-D][Tester D] Sort by Names When Names are Numbers
Since your application allows names to be pure numbers, when utilising your application, it's worth noting that if I execute the command "sort /name," it will arrange all the numbers at the beginning, which might not be aesthetically pleasing.

Command: sort /name

Suggestions: Maybe should limit users from employing numbers as names, and when sorting by names, only alphabetical names should be taken into account.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: linnn-7/ped#7

### LINKED ISSUE #130: [PE-D][Tester D] Need Troubleshooting for Import/Migrate features in User Guide
I have encountered an issue where, during the import or migration of files, Excel may automatically delete preceding "0"s in the StudentId field, resulting in failed import or migration commands. It would be beneficial if users could be alerted about this potential occurrence in your user guide.

Screenshot:
Excel automatically removes preceding "0"s:

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: linnn-7/ped#9

### PR DESCRIPTION
**Pull request by ongzhili**
Adds documentation regarding leading zeroes (as mentioned by #130 )

### CODE REVIEW

**Review by wallacexuhanxiao — APPROVED** [review]
LGTM!

**Comment by ongzhili** [comment]
Added another disclaimer regarding names with `-` and `/`, as well as names with numeric characters. I've put it under Known Issues, but would like some suggestions on where it should be placed instead.

**Comment by ongzhili** [comment]
For names containing numeric characters: They do exist

See: https://en.wikipedia.org/wiki/Jennifer_8._Lee

**Review by wallacexuhanxiao — APPROVED** [review]
LGTM! If I am the reviewer, I won't post issues on Names constraints after reading this!

**Review by J-wang-CSMA — APPROVED** [review]
LGTM!

**Pull request merged**
